app = "automacaoteste"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = "10s"

[build]
  dockerfile = "Dockerfile"

[env]
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  N8N_PROTOCOL = "https"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "senha123"
  WEBHOOK_URL = "https://automacaoteste.fly.dev"
  N8N_EDITOR_BASE_URL = "https://automacaoteste.fly.dev"
  NODE_ENV = "production"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[vm]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
