app = "automacaoteste"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "senha123"
  N8N_HOST = "0.0.0.0"
  WEBHOOK_URL = "https://automacaoteste.fly.dev/"


[experimental]
  allowed_public_ports = [5678]
  auto_rollback = true

[deploy]
  release_command = "npx n8n update:all"

[build]
  image = "n8nio/n8n:latest"


[metrics]
  port = 9090

[[services]]
  internal_port = 5678
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services.tcp_checks]]
  interval = 10000
  timeout = 2000
  grace_period = "10s"

